spring.application.name=bank.sim

external-api.exchange.base-url: https://api.frankfurter.dev/v2/

security.jwt.secret-key: 3f0983ef5a0613cafed3d8e4d6052f3274d7a20d3274f0a8546e027fbb61a6cd
security.jwt.expiration-secs: 3600
